web:
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./public:/usr/share/www
        - ./nginx/:/etc/nginx/conf.d/

        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./public:/usr/share/www

mysql:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: admin
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
        - mysql
    ports:
        - 8183:80
    environment:
        MYSQL_USERNAME: admin
        MYSQL_ROOT_PASSWORD: admin
        PMA_ARBITRARY: 1